language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - sudo apt-get install graphviz
  - "python setup.py install"
  - "pip install nose==1.3.7 coverage==4.3.4 coveralls"
  - "pip install isort==4.3.4 pycodestyle==2.3.1 pydocstyle==2.1.1"
  - "pip list"

script:
  - nosetests
  - pycodestyle
  - pydocstyle
  - isort --check-only

after_success:
  coveralls
