language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - sudo apt-get install graphviz
  - "python setup.py install"
  - "pip install nose==1.3.7"
  - "pip install coverage==4.3.4"
  - "pip install coveralls"
  - "pip list"

script:
  - nosetests

after_success:
  coveralls
